Made new changes.
getkevin/kevin-prestashop pull request #1
Opened 2022-01-17 13:46 UTC by xpresas

Updated various places and fixed some bugs.

2022-01-18 13:03 UTC, saltanovas requested changes

2022-01-19 14:13 UTC, xpresas commented on controllers/front/redirect.php
>          $bank_id = Tools::getValue('id');
Your old developer left some stuff... :)

2022-01-19 14:21 UTC, xpresas commented on controllers/front/redirect.php
>          }
I wont lie this looks weird to me too. But probably the developer who made this. Did it with an idea that if the line below returns null or the row doesnt exists at all the code wouldnt break.
`$redirect_preferred = Configuration::get('KEVIN_REDIRECT_PREFERRED');`
Return nothing (Configuration::get($key) searches ps_configuration table on DB and returns the value by the given key). 

Currently this doesnt even make sense and will be revorked at some point by us.

2022-01-19 14:21 UTC, xpresas commented on controllers/front/redirect.php
> +                ];
PhpStorms autoformatter :)

2022-01-19 14:23 UTC, xpresas commented on controllers/front/webhook.php
>          }
Why would it break? https://www.php.net/manual/en/function.exit.php
When the module is disabled the execution of webhook.php stops.

2022-01-19 14:27 UTC, xpresas commented on kevin.php
> -            ),
I speculate that the the developer who did this before us just didnt wanted to implement custom order statuses everywhere anymore. So he just deleted these 2 and kept using the default prestashop ones. (Which in my eyes is a better way to do because you dont need to support these 2 in many more other places)

2022-01-19 14:28 UTC, xpresas commented on kevin.php
> +        $this->limited_currencies = array('EUR','PLN','BGN','HRK','CZK','DKK','HUF','RON','SEK','CHF');
you should ask your manager Arturas.

2022-01-19 14:41 UTC, saltanovas commented on controllers/front/webhook.php
>          }
Yeah, I know what `exit` does :) Such logical operation was written by the previous developer, but I am just curious why we have this `if` statement here? Would the code break if we process the webhook even if the module is disabled?

2022-01-19 14:43 UTC, saltanovas commented on kevin.php
> +        $this->limited_currencies = array('EUR','PLN','BGN','HRK','CZK','DKK','HUF','RON','SEK','CHF');
Told that limitations was added by the previous developer anyways. But I expect card payment method to be returned when the country with no integrated banks is selected. Let's leave it as it is now.

2022-01-19 14:50 UTC, xpresas commented on controllers/front/webhook.php
>          }
Prestashop does actually try to check if file should be even accessable if the module is disabled. But I can only speculate that the developer who made this just wanted to have an extra layer of security for various bots and other bad people. :) Doesnt take much time to write it

2022-01-19 14:52 UTC, saltanovas commented on controllers/front/redirect.php
>          }
Well, I trust you and I hope that you won't forget to refactor it :)

2022-01-19 14:54 UTC, xpresas commented on controllers/front/redirect.php
>          }
Probably at some point we will just remake the whole module itself. 
Now we are just patching the things up left by the old dev. Which is a pain in itself. LOL.

2022-01-19 15:08 UTC, saltanovas commented on controllers/front/redirect.php
> +
With the latest PHP library, client can be created with `$lang` option. Can be improved with the future release:

```
$options = ['error' => 'array', 'version' => '0.3', 'lang' => 'en'];
$kevinClient = new Client($clientId, $clientSecret, $options);
```

2022-01-19 15:08 UTC, saltanovas approved these changes
@xpresas change info@getkevin.eu to help@kevin.eu everywhere and then Iit can be merged

2022-01-21 11:58 UTC, merged