Fix Prestashop 1.6 fallback error
getkevin/kevin-prestashop pull request #5
Opened 2022-04-04 09:19 UTC by saltanovas

2022-04-04 09:21 UTC, saltanovas commented
@xpresas is everything done with Prestashop 1.6 fallback error page? How about country and currency limitations, did you manage to remove them?

2022-04-04 09:35 UTC, tomas-maciulis requested changes

2022-04-04 09:35 UTC, tomas-maciulis commented on controllers/front/redirect.php
> +            if (version_compare(PS_VERSION, '1.7.0') < 0) {
if (version_compare(PS_VERSION, '1.7.0', '<')) {
...
}

2022-04-19 07:31 UTC, tomas-maciulis requested changes
Please also make sure your code style matches our standards https://github.com/getkevin/kevin-prestashop#contributing

2022-04-19 07:31 UTC, tomas-maciulis commented on controllers/front/webhook.php
> +                                $sql = 'SELECT id_order_state FROM ' . DB_PREFIX . 'order_history WHERE id_order_state = ' . (int) $new_os_id . ' AND id_order = ' . (int) $order->id;
If I understand correctly, it only prevents updates when there's already a record for given status in the history. It should prevent failed, payment received or completed order from being touched, too.

2022-04-19 10:50 UTC, xpresas commented on controllers/front/webhook.php
> +                                $sql = 'SELECT id_order_state FROM ' . DB_PREFIX . 'order_history WHERE id_order_state = ' . (int) $new_os_id . ' AND id_order = ' . (int) $order->id;
It prevents the same status for being set twice by the payment gateway's webhook. It doesnt matter if its failed, payment received, completed or any other status. It always should be only set once.

2022-04-20 10:45 UTC, tomas-maciulis commented on controllers/front/webhook.php
> +                                $sql = 'SELECT id_order_state FROM ' . DB_PREFIX . 'order_history WHERE id_order_state = ' . (int) $new_os_id . ' AND id_order = ' . (int) $order->id;
That's good but we're having problems with completed/paid orders set to failed by webhooks. Imagine this scenario:

1. Client starts kevin. payment and changes their mind before completing it
2. Client pays in some other way and administrator or another plugin changes order status to payment received or manages to complete an order within a day
3. 2 days later kevin. payment expires and webhook is sent for a failed payment changing payment received or order completed status to failed even though it has already been paid for and possibly even shipped.

It should not be possible for webhook to downgrade order status like that.

2022-04-25 12:20 UTC, tomas-maciulis requested changes

2022-04-25 12:20 UTC, tomas-maciulis commented on controllers/front/webhook.php
> +                                if (!$isStatusDuplicate) {
It would be better to use an array to store immutable statuses to make the list easy to modify as such:

```
$immutableStatuses = implode(',', [
  (int) Configuration::get('PS_OS_PAYMENT'),
  (int) Configuration::get('PS_OS_PREPARATION'),
....
];
```

2022-04-27 12:27 UTC, tomas-maciulis approved these changes

2022-05-03 06:00 UTC, tomas-maciulis approved these changes

2022-05-03 06:00 UTC, merged