TS-367: ignore webhook if order is cancelled
getkevin/kevin-prestashop pull request #7
Opened 2022-05-09 20:33 UTC by tomas-maciulis

2022-05-10 06:51 UTC, saltanovas requested changes

2022-05-10 06:51 UTC, saltanovas commented on translations/en.php
>  $_MODULE['<{kevin}prestashop>kevin_3e984424a2dcd938412cace671b40e59'] = 'Payment is Pending';
Perhaps lowercase `Pending` then as well?

2022-05-10 06:59 UTC, saltanovas approved these changes

2022-05-10 06:59 UTC, saltanovas commented
Do we need QA here? :D I would say just merge

2022-05-12 11:20 UTC, merged

2022-05-12 11:20 UTC, xpresas commented
Couldn't wait for you guys to merge.

2022-05-12 12:21 UTC, saltanovas commented
@xpresas we always do QA now. If you need features from a specific branch, you should checkout that specific feature branch and open a pull request on it.

We will try to do define some restrictions in the feature.

2022-05-12 13:09 UTC, saltanovas commented
If you have in mind manual tests from developer side, then yes, and it is extremely valuable :) But we do have internal dedicated people to ensure the overall plugin quality